### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by maxschram** [aellison1558/Capstone_project_proposal#2]
In phase 3 are tags the same as categories? How will you implement the fuzzy search of the project's contents?

**Comment by aellison1558** [comment]
Hey Max,

Thanks for the feedback.  Initially I had tags as a thing.  As I was planning the project felt that tags were redundant with categories and removed them.  Guess I forgot to update the search.

On that note not entirely sure how to do a fuzzy search.  Is there a gem for that?
